import { EntryStatus, OliveType, Permission } from '@prisma/client';

import { OLIVE_TYPE_PRINT } from './olive-type-labels';

export const OLIVE_TYPE_AR: Record<OliveType, string> = {
  GREEN: OLIVE_TYPE_PRINT.GREEN.labelAr,
  RIPE: OLIVE_TYPE_PRINT.RIPE.labelAr,
  ZBOUCH: OLIVE_TYPE_PRINT.ZBOUCH.labelAr,
};

export const ENTRY_STATUS_AR: Record<EntryStatus, string> = {
  RECEIVED: 'مستلم',
  IN_STORAGE: 'في المخزن',
  PRESSED: 'معصور',
  OIL_COLLECTED: 'تم استلام الزيت',
  PAID: 'مدفوع',
  COMPLETED: 'مكتمل',
  CANCELLED: 'ملغى',
};

export const PERMISSION_LABELS_AR: Record<Permission, string> = {
  USERS_READ: 'قراءة المستخدمين',
  USERS_WRITE: 'إدارة المستخدمين',
  CLIENTS_READ: 'قراءة الزبائن',
  CLIENTS_WRITE: 'إدارة الزبائن',
  OLIVE_READ: 'قراءة استقبال الزيتون',
  OLIVE_WRITE: 'إدارة استقبال الزيتون',
  PRESSING_READ: 'قراءة التصفية',
  PRESSING_WRITE: 'إدارة التصفية',
  FILTRATION_READ: 'قراءة تصفية الزيت',
  FILTRATION_WRITE: 'إدارة تصفية الزيت',
  FINANCE_READ: 'قراءة المالية',
  FINANCE_WRITE: 'إدارة المالية',
  SETTINGS_READ: 'قراءة الإعدادات',
  SETTINGS_WRITE: 'إدارة الإعدادات',
  REPORTS_READ: 'التقارير',
  AUDIT_READ: 'سجل النشاط',
  BACKUP_RESTORE: 'النسخ الاحتياطي',
  OIL_SALES_READ: 'عرض بيع الزيت',
  OIL_SALES_WRITE: 'إنشاء بيع الزيت',
  OIL_SALES_CANCEL: 'إلغاء بيع الزيت',
  OIL_STOCK_WRITE: 'إدارة مخزون الزيت',
  OIL_INVENTORY_WRITE: 'جرد مخزون الزيت',
  OIL_CUSTOMERS_WRITE: 'إدارة زبائن بيع الزيت',
  OIL_SALES_SETTINGS: 'إعدادات بيع الزيت',
  OIL_SALES_OVERRIDE: 'تجاوز مخزون البيع',
  MILL_ACCESS: 'دخول مساحة المعصرة',
  OIL_SALES_ACCESS: 'دخول مساحة بيع الزيت',
  OIL_SALES_DASHBOARD_VIEW: 'عرض لوحة بيع الزيت',
  OIL_SALES_SALES_VIEW: 'عرض المبيعات',
  OIL_SALES_SALES_CREATE: 'إنشاء بيع',
  OIL_SALES_SALES_EDIT: 'تعديل بيع',
  OIL_SALES_SALES_CANCEL: 'إلغاء بيع',
  OIL_SALES_SALES_DELETE: 'حذف بيع',
  OIL_SALES_SALES_REPRINT: 'إعادة طباعة وصل',
  OIL_SALES_SALES_CHANGE_PRICE: 'تغيير سعر البيع',
  OIL_SALES_SALES_ALLOW_DEBT: 'بيع بالدين',
  OIL_SALES_DEBTS_VIEW: 'عرض الديون',
  OIL_SALES_DEBTS_RECORD_PAYMENT: 'تسجيل تسديد',
  OIL_SALES_DEBTS_VIEW_ALL: 'عرض كل الديون',
  OIL_SALES_DEBTS_ADJUST: 'تسوية دين',
  OIL_SALES_DEBTS_EXPORT: 'تصدير الديون',
  OIL_SALES_ASSISTANCE_FIXED: 'مساعدة ثابتة',
  OIL_SALES_ASSISTANCE_PERCENT: 'مساعدة نسبة',
  OIL_SALES_ASSISTANCE_PER_LITRE: 'مساعدة لكل لتر',
  OIL_SALES_ASSISTANCE_MODIFY: 'تعديل المساعدة',
  OIL_SALES_ASSISTANCE_TOTALS: 'عرض إجمالي المساعدات',
  OIL_SALES_STOCK_VIEW: 'عرض المخزون',
  OIL_SALES_STOCK_ADD: 'إضافة مخزون',
  OIL_SALES_STOCK_ADJUST: 'تصحيح المخزون',
  OIL_SALES_STOCK_LOSS: 'عرض الخسارة',
  OIL_SALES_STOCK_OVERRIDE: 'تجاوز المخزون',
  OIL_SALES_INVENTORY_VIEW: 'عرض الجرد',
  OIL_SALES_INVENTORY_CREATE: 'تسجيل جرد',
  OIL_SALES_CUSTOMERS_VIEW: 'عرض زبائن البيع',
  OIL_SALES_CUSTOMERS_CREATE: 'إضافة زبون بيع',
  OIL_SALES_CUSTOMERS_EDIT: 'تعديل زبون بيع',
  OIL_SALES_CUSTOMERS_DELETE: 'حذف زبون بيع',
  OIL_SALES_CONTAINERS_VIEW: 'عرض التعبئة',
  OIL_SALES_CONTAINERS_CREATE: 'إضافة تعبئة',
  OIL_SALES_CONTAINERS_EDIT: 'تعديل تعبئة',
  OIL_SALES_CONTAINERS_DELETE: 'حذف تعبئة',
  OIL_SALES_CONTAINERS_SELL: 'بيع ضلف فارغة',
  OIL_SALES_CONTAINERS_CHANGE_PRICE: 'تغيير سعر الضلف',
  OIL_SALES_CONTAINER_STOCK_VIEW: 'عرض مخزون الضلف',
  OIL_SALES_CONTAINER_STOCK_ADD: 'إضافة مخزون ضلف',
  OIL_SALES_CONTAINER_STOCK_ADJUST: 'تصحيح مخزون الضلف',
  OIL_SALES_CONTAINER_STOCK_INVENTORY: 'جرد الضلف',
  OIL_SALES_CONTAINER_STOCK_LOSS: 'تلف / فقدان الضلف',
  OIL_SALES_CONTAINER_STOCK_OVERRIDE: 'تجاوز مخزون الضلف',
  OIL_SALES_CASH_REGISTER_OPEN: 'فتح الصندوق',
  OIL_SALES_CASH_REGISTER_CLOSE: 'إغلاق الصندوق',
  OIL_SALES_CASH_REGISTER_VIEW_OWN: 'عرض الصندوق الحالي',
  OIL_SALES_CASH_REGISTER_VIEW_ALL: 'عرض كل الصناديق',
  OIL_SALES_CASH_REGISTER_ADJUST: 'تعديل حركة الصندوق',
  OIL_SALES_CASH_REGISTER_VIEW_DIFFERENCES: 'عرض فروقات الصندوق',
  OIL_SALES_DEVICES_VIEW: 'عرض أجهزة البيع',
  OIL_SALES_DEVICES_MANAGE: 'إدارة أجهزة البيع',
  MILL_DEVICES_VIEW: 'عرض أجهزة المعصرة',
  MILL_DEVICES_MANAGE: 'إدارة أجهزة المعصرة',
  OIL_SALES_REPORTS_VIEW: 'عرض تقارير البيع',
  OIL_SALES_REPORTS_EXPORT: 'تصدير التقارير',
  OIL_SALES_PRINT_RECEIPT: 'طباعة وصل البيع',
  OIL_SALES_SETTINGS_VIEW: 'عرض إعدادات البيع',
  OIL_SALES_SETTINGS_EDIT: 'تعديل إعدادات البيع',
};
